contact_links:
  - name: Give your feedback ðŸ“£
    url: https://github.com/thomvaill/log4brains/discussions/new?category=Feedback
    about: Give your feedback
  - name: Ask a question
    url: https://github.com/thomvaill/log4brains/discussions
    about: Ask questions and discuss with other community members
